archives:
- id: channelz-ui
  files:
    - README.md
    - LICENSE
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates:
    - "bonnefoa/channelz-ui:{{ .Tag }}"
    - "bonnefoa/channelz-ui:v{{ .Major }}"
    - "bonnefoa/channelz-ui:v{{ .Major }}.{{ .Minor }}"
    - "bonnefoa/channelz-ui:latest"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/bonnefoa/channelz-ui
      - --label=org.opencontainers.image.source=https://github.com/bonnefoa/channelz-ui
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: bonnefoa
    name: channelz-ui
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
